config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'
  resources :jobs , except: [:index, :new]

end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
    belongs_to :companies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    def index
        @companies = Company.all
        @company = Company.new
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:edit, :update, :destroy]
  def index
    @jobs = Job.all
    @job = Job.new
  end
  
  def create
    @job = Job.new(job_params)
    @job.save
    redirect_to root_path , notice: 'お仕事を保存しました'
  end
  
  def edit
  end
  
  def update
    if @job.update(job_params)
      redirect_to job_path(@job) , notice: 'お仕事を保存しました'
    else
      render 'edit'
    end
  end
  
  def destroy
    @job.destroy
    redirect_to root_path, notice: 'お仕事を削除しました'
  end
  
  def show
    @job = Job.find(params[:id])
  end
  
  private
  def job_params
    params.require(:job).permit(:company, :companyread, :name, :address, :stationline, :station, :stationdistance, :description, :requiredskills, :salary, :hours, :overtime, :holidays, :welfare, :number, :visasupport, :employmenttype, :worktype)
  end
  
  def set_job
    @job = Job.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <td>会社名</td>
            <td><%= f.text_field :companyread, :class => "form-control" %><br><%= f.text_field :company, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>募集職種</td>
            <td><%= f.text_field :name, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>募集人数</td>
            <td><%= f.text_field :number, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>業務内容</td>
            <td><%= f.text_area :description, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>求めるスキル・経験・経歴</td>
            <td><%= f.text_area :requiredskills, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>雇用形態</td>
            <td><%= f.select(:employmenttype, options_for_select([['', 0], ['正社員', 1], ['契約社員', 2], ['派遣社員', 3], ['アルバイト', 4], ['委託', 5]]), {}, { :class => "form-control" }) %></td>
        </tr>
        <tr>
            <td>給与条件</td>
            <td><%= f.text_field :salary, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>勤務時間</td>
            <td><%= f.text_field :hours, :class => "form-control" %><br><%= f.radio_button :worktype,0 %>フルタイム<%= f.radio_button :worktype,1 %>パートタイム</td>
        </tr>
        <tr>
            <td>残業</td>
            <td><%= f.text_field :overtime, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>休日・休暇</td>
            <td><%= f.text_field :holidays, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>福利厚生</td>
            <td><%= f.text_field :welfare, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>勤務地住所</td>
            <td><%= f.text_field :address, :class => "form-control" %></td>
        </tr>
        <tr>
            <td>ビザサポート</td>
            <td><%= f.radio_button :visasupport,0 %>無<%= f.radio_button :visasupport,1 %>有</td>
        </tr>
        <tr>
            <td>最寄り駅</td>
            <td>路線: <%= f.text_field :stationline, :class => "form-control" %><br>駅名: <%= f.text_field :station, :class => "form-control" %></td>
        </tr>
    </table>

    <%= f.submit :class => "btn btn-block btn-lg btn-primary" %>

<% end %>

app/views/jobs/edit.html.erb
<h1>お仕事の編集</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<h1>全募集職欄</h1>

<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>案件ID</th>
        <th>会社名</th>
        <th>募集職種</th>
        <th>募集人数</th>
        <th>雇用形態</th>
        <th>給与条件</th>
        <th>勤務時間</th>
        <th>最寄り駅</th>
    </tr>
    <% @jobs.each do |job| %>
    <tr data-link="<%= job_path(job) %>" style="cursor:pointer;">
        <td><%= job.id %></td>
        <td><%= job.companyread %><br><%= job.company %></td>
        <td><%= job.name %></td>
        <td><%= job.number %></td>
        <td>
            <% if job.employmenttype == 0 %>
            <% elsif job.employmenttype == 1 %>
                正社員
            <% elsif job.employmenttype == 2 %>
                契約社員
            <% elsif job.employmenttype == 3 %>
                派遣社員
            <% elsif job.employmenttype == 4 %>
                アルバイト
            <% elsif job.employmenttype == 5 %>
                委託
            <% else %>
                (未登録)
            <% end %>
        </td>
        <td><%= job.salary %></td>
        <td><%= job.hours %></td>
        <td><%= job.stationline %><br><%= job.station %></td>
    </tr>
    <% end %>
</table>

<%= render 'form' %>

app/views/jobs/show.html.erb
<h1>お仕事の詳細</h1>

<table class="table table-striped table-bordered table-hover">
    <tr>
        <td>会社名:</td>
        <td><%= @job.companyread %><br><%= @job.company %></td>
    </tr>
    <tr>
        <td>募集職種:</td>
        <td><%= @job.name %></td>
    </tr>
    <tr>
        <td>募集人数:</td>
        <td><%= @job.number %>名</td>
    </tr>
    <tr>
        <td>業務内容:</td>
        <td><%= @job.description %></td>
    </tr>
    <tr>
        <td>求めるスキル・経験・経歴:</td>
        <td><%= @job.requiredskills %></td>
    </tr>
    <tr>
        <td>雇用形態:</td>
        <td>
            <% if @job.employmenttype == 0 %>
            <% elsif @job.employmenttype == 1 %>
                正社員
            <% elsif @job.employmenttype == 2 %>
                契約社員
            <% elsif @job.employmenttype == 3 %>
                派遣社員
            <% elsif @job.employmenttype == 4 %>
                アルバイト
            <% elsif @job.employmenttype == 5 %>
                委託
            <% else %>
                (未登録)
            <% end %>
        </td>
    </tr>
    <tr>
        <td>給与条件:</td>
        <td><%= @job.salary %></td>
    </tr>
    <tr>
        <td>勤務時間</td>
        <td><%= @job.hours %> （勤務形態: <% if @job.worktype == 0 %>フルタイム<% elsif @job.worktype == 1 %>パートタイム<% else %>未登録<% end %>）</td>
    </tr>
    <tr>
        <td>残業</td>
        <td><%= @job.overtime %></td>
    </tr>
    <tr>
        <td>休日・休暇:</td>
        <td><%= @job.holidays %></td>
    </tr>
    <tr>
        <td>福利厚生:</td>
        <td><%= @job.welfare %></td>
    </tr>
    <tr>
        <td>勤務地住所:</td>
        <td><%= @job.address %></td>
    </tr>
    <tr>
        <td>ビザサポート:</td>
        <td>
            <% if @job.visasupport == 0 %>
                無
            <% elsif @job.visasupport == 1 %>
                有
            <% else %>(未登録)
            <% end %>
        </td>
    </tr>
    <tr>
        <td>最寄り駅:</td>
        <td>路線: <%= @job.stationline %><br>駅: <%= @job.station %></td>
    </tr>
</table>

<%= link_to "編集" , edit_job_path(@job) , :class => "btn btn-primary btn-block btn-lg" %>

<%= link_to "削除" , @job , method: :delete , :class => "btn btn-danger btn-block btn-lg" , data: { confirm: '削除しますよ？！' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shigotodayo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<style>
  body {
    font-family:Meiryo,メイリオ;
  }
  .jumbotron {
    background-position: center center;
    background-size: cover;
    background-repeat: no-repeat;
    width:100%;
    display:table;
    margin:0;
    text-shadow: 0 0 10px #fff;
  }
  footer {
    margin-top:100px;
    padding:20px;
    color:#9d9d9d;
    background-color:#222;
  }
  .table > tbody > tr > td {
     vertical-align: middle;
  }
</style>
<body>
  <div class="jumbotron" style="background-image:url('https://lh3.googleusercontent.com/-BACCS18L-Jo/VPlfWrXIWBI/AAAAAAAAACI/c4lI3R-9Bpg/w2048-h1365-no/IMG_9737.jpg');">
    <div class="jumbotroncontent">
      <div class="container">
        <h1>GlobalPower<br>Placement<br>Information<br>Services</h1>
      </div>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Shigotodayo</a>
      </div>
    </div>
  </nav>
  <footer>
    <div class="container">
      &copy; 2015 Terry Kimura CC-BY-SA<!-- with love from T to M -->
    </div>
  </footer>

</body>
</html>